### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by fdch** [tmhglnd/max-pd-converter#3]
```
$ npm start /usr/local/lib/pd/extra/rev3~.pd 

> max-pd-convert@1.0.0 start max-pd-converter
> node main.js "/usr/local/lib/pd/extra/rev3~.pd"

max-pd-converter/main.js:108
	let pat = { ...patchTemplate };
	            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! max-pd-convert@1.0.0 start: `node main.js "/usr/local/lib/pd/extra/rev3~.pd"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the max-pd-convert@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**Comment by fdch** [comment]
Got that on maocs trying to convert a pd patch to maxpat. Hope it helps debugging! Best

**Comment by tmhglnd** [comment]
You will have to update your local Node version to a greater version than `8.6.0` if i'm not mistaken. Check your version with `$ node -v`
