### ISSUE TITLE
Fail convertion max to pd in linux ubuntu studio

### ISSUE THREAD

**Issue by low-bin** [tmhglnd/max-pd-converter#4]
> max-pd-convert@1.0.0 start /home/vito-lobin/max-pd-converter
> node main.js "/home/vito-lobin/Documentos/ARTE/Performances/bsblork/chuva_radioativa/Fallout.0.3.2.maxpat"

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vito-lobin/max-pd-converter/main.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! max-pd-convert@1.0.0 start: `node main.js "/home/vito-lobin/Documentos/ARTE/Performances/bsblork/chuva_radioativa/Fallout.0.3.2.maxpat"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the max-pd-convert@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vito-lobin/.npm/_logs/2020-10-16T21_49_14_616Z-debug.log

**Comment by tmhglnd** [comment]
Most likely you have not yet installed the node modules by running the `$ npm install` command
